routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TasksController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'App\Http\Controllers\TasksController@index');
Route::resource('tasks', TasksController::class, ['except' => ['show']]);

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'conts',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use Illuminate\Http\Request;

class TasksController extends Controller
{
	public function index()
	{
        $tasks = Task::orderBy('created_at', 'asc')
        	->paginate(5);

        $here = "tasks";

        return view('tasks.index',compact('tasks','here'));
	}

    public function create()
    {
    	$here = "tasks";

        return view('tasks.create', compact('here'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255|min:3|unique:tasks',
        ]);

        $input = $request->all();

		try {
	        $task = Task::create($input);

	        return redirect()->route('tasks.index')
	        	->with('status','Задача #'.$task->id.' успешно создана');
		} catch(\Illuminate\Database\QueryException $ex) {
			return redirect()->route('tasks.index')
				->with('error','Ошибка создания задачи #'.$task->id);
		}
    }

    public function edit($id)
    {
        $task = Task::findOrFail($id);

		$here = "tasks";

        return view('tasks.edit', compact('task','here'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string|max:255|min:3|unique:tasks,name,'.$id,
        ]);

		$task = Task::findOrFail($id);

        $input = $request->all();
		
		try {
        	$task->update($input);

        	return redirect()->route('tasks.index')
				->with('status','Задача #'.$task->id.' успешно обновлена');
        } catch(\Illuminate\Database\QueryException $ex) {
        	return redirect()->route('tasks.index')
				->with('error','Ошибка обновления задачи #'.$task->id);
        }
    }

    public function destroy($id)
    {
        $task = Task::select('id')->findOrFail($id);

		try {
	        $task->delete();

	        return redirect()->route('tasks.index')
				->with('status','Задача #'.$task->id.' успешно удалена');
		} catch(\Illuminate\Database\QueryException $ex) {
			return redirect()->route('tasks.index')
				->with('error','Ошибка удаления задачи #'.$task->id);
		}
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <meta name="description" content="@yield('description')">

        <script>document.getElementsByTagName("html")[0].className += " js";</script>

        <title>@yield('title')</title>

        <!-- Fonts -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/stylesheet.css') }}">
        <link rel="stylesheet" href="{{ asset('/css/fancybox.css') }}">
        <link rel="stylesheet" href="{{ asset('/js/timeline/css/style.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('/js/app.js') }}" defer></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <script src="{{ asset('/js/fancybox-1.2.6.js') }}"></script>
        <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js?skin=default"></script>
        <script src="{{ asset('/js/site.js') }}"></script>
    </head>
    <body>
        <div class="wrapper">
            <header>
                @include('layouts.elements.menu')
            </header>
            
            <!-- Page Content -->
             <div class="container">
				<div class="row">
					<div class="col">
						@include('layouts.elements.mess')
                        @yield('content')
                    </div>
                 </div>
             </div>
             
            <div class="empty">&nbsp;</div>
        </div>
        <footer id="footer" class="footer navbar-fixed-bottom">
            <div class="container">
                <div class="text-center">Property of ProgPHP group. All rights reserved &copy; @php echo date('Y'); @endphp</div>
            </div>
        </footer>
        <!--script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" crossorigin="anonymous" async></script-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
        <script src="{{ asset('/js/timeline/js/util.js') }}"></script>
		<script src="{{ asset('/js/timeline/js/swipe-content.js') }}"></script>
		<script src="{{ asset('/js/timeline/js/main.js') }}"></script>
    </body>
</html>

resources/views/layouts/elements/menu.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
    	<a class="nav-link text-center @if(isset($here) && $here=='tasks') active @endif" href="/">Главная</a>
      </div>
    </div>
    <div class="container text-center" style="max-width: 200px;">
		<a class="navbar-brand" href="/">
			<img src="/img/logo_w.png" width="120" height="40" class="d-inline-block align-top" alt="" loading="lazy">
		</a>
    </div>
  </div>
</nav>

resources/views/layouts/elements/mess.blade.php
@if (session('status') || session('error') || $errors->any())
    <div class="container">
         <div class="row">
                <div class="col">
                    @if (session('status'))
                    <div class="alert bg-success text-light">
                        {{ session('status') }}
                    </div>
                    @endif
                    @if (session('error'))
                        <div class="alert bg-danger text-light">
                            {{ session('error') }}
                        </div>
                    @endif
                    @if($errors->any())
                        <div class="alert bg-danger text-light">{!! implode('<br />', $errors->all(':message')) !!}</div>
                    @endif
                </div>
          </div>
    </div>
@endif

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('title', 'Новая Задача')
@section('description', 'Новая Задача')

@section('content')
	<div>
		<h2>Новая Задача</h2>

		<form method="post" action="{{ route('tasks.store') }}">
	        @csrf
		    
		    <div class="container">
		    	<div class="row">
		    		<div class="col mt-2">
		    			Название
		    		</div>
		    	</div>
		    	<div class="row">
		    		<div class="col">
		    			<input type="text" name="name" class="form-group w-100" value="{{ old('name') }}" />
		    		</div>
		    	</div>
		    	<div class="row mt-2">
		    		<div class="col">
		    			Описание
		    		</div>
		    	</div>
		    	<div class="row">
		    		<div class="col">
		    			<textarea name="conts" class="form-control" rows="12">{{ old('conts') }}</textarea>
		    		</div>
		    	</div>
		    </div>

			<p>&nbsp;</p>

			<div class="container buttons_block">
	        	<div class="row text-center justify-content-center">
	        		<div class="buttons_block_sub" style="width: 400px;">

	        			<div class="container">
	        				<div class="row">
								<div class="col">
						            <button class="" type="submit">Сохранить</button>
						        </div>
						        <div class="col"><a href="{{ route('tasks.index') }}">Отмена</a></div>
						    </div>
						</div>

			    	</div>
				</div>
	        </div>
	        
	    </form>
    </div>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('title', 'Редактирование задачи '.$task->id)
@section('description', 'Редактирование задачи '.$task->id)

@section('content')
	<div class="admin-form">
		<h2>Редактирование задачи "{{ $task->id }}"</h2>

		<form method="post" action="{{ route('tasks.update', $task->id) }}">
	        @method('PATCH')
		    @csrf

		    <div class="container">
		    	<div class="row">
		    		<div class="col mt-2">
		    			Название
		    		</div>
		    	</div>
		    	<div class="row">
		    		<div class="col">
		    			<input type="text" name="name" class="form-group w-100" value="{{ old('name') ?? $task->name ?? '' }}" />
		    		</div>
		    	</div>
		    	<div class="row mt-2">
		    		<div class="col">
		    			Описание
		    		</div>
		    	</div>
		    	<div class="row">
		    		<div class="col">
		    			<textarea name="conts" class="form-control" rows="12">{{ old('conts') ?? $task->conts ?? '' }}</textarea>
		    		</div>
		    	</div>
		    </div>

			<p>&nbsp;</p>

			<div class="container buttons_block">
	        	<div class="row text-center justify-content-center">
	        		<div class="buttons_block_sub" style="width: 400px;">

	        			<div class="container">
	        				<div class="row">
								<div class="col">
						            <button class="" type="submit">Сохранить</button>
						        </div>
						        <div class="col"><a href="{{ route('tasks.index') }}">Отмена</a></div>
						    </div>
						</div>

			    	</div>
				</div>
	        </div>
	        
	    </form>
    </div>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('title', 'ToDo List')
@section('description', 'ToDo List')

@section('content')

<div class="container">

	<h2>ToDo List</h2>

	<p>&nbsp;</p>

	<div class="row">
		<div class="col text-center">
			<a class="act_butt" href="{{ route('tasks.create') }}">новая задача</a>
		</div>
	</div>

	<p>&nbsp;</p>

	@if(count($tasks) > 0)
		<div class="row">
			<div class="col">
				{!! $tasks->appends(Request::except('page'))->render() !!}
			</div>
			<div class="col text-end">
				Всего задач: {{ $tasks->total() }}
			</div>
		</div>

		<hr />

		@foreach ($tasks as $task)
			<div class="row">
				<div class="col">
					<div>
						<strong>{{ $task->name }} (#{{ $task->id }})</strong><br />
						{{ $task->conts }}<br />
					</div>
					<div class="text-muted text-end">
						Создано: {{ $task->created_at }}<br />
						Обновлено: {{ $task->updated_at }}
					</div>
					<div class="actions">
						<a class="act_butt" title="Редактировать" href="{{ route('tasks.edit', $task->id) }}">редактировать</a>

						<form action="{{ route('tasks.destroy', ['task' => $task->id]) }}"
							method="post" onsubmit="return confirm('Вы действительно хотите удалить задачу {{ $task->id }} ?')">
							@csrf
							@method('DELETE')
								<button type="submit" title="Удалить" class="act_butt m-0 border-0 bg-transparent text-primary"><u>удалить</u></button>
						</form>
					</div>
				</div>
			</div>
			<hr />
		@endforeach

		<div class="row">
			<div class="col">
				{!! $tasks->appends(Request::except('page'))->render() !!}
			</div>
			<div class="col text-end">
				Всего задач: {{ $tasks->total() }}
			</div>
		</div>
	@else
		<div class="row">
			<div class="col">задачи еще не созданы</div>
		</div>
	@endif

	<p>&nbsp;</p>

	<div class="row">
		<div class="col text-center">
			<a class="act_butt" href="{{ route('tasks.create') }}">новая задача</a>
		</div>
	</div>

	<p>&nbsp;</p>

</div>
@endsection